version: '2'
services:
  repetitionhandler1:
    image: remeeh/repetitionhandler:latest
    volumes:
     - C:\datasets\disa:/opt/docker/data

  repetitionhandler2:
    image: remeeh/repetitionhandler:latest
    volumes:
     - C:\datasets\disa:/opt/docker/data

  recalltest:
    image: remeeh/recalltest:latest
    #command: --data data/0/descriptors-1-million-reduced-128-hamming-256bit.data --dataeuc data/0/descriptors-1-million-reduced-128-normalized.data --size 1008263 --dimensions 256 --dataType binary --nodesAddresses data/0/ips --testCases data/0/testcases --invocationCount 10 --warmUpIterations 1 --out data/0/out --seed 1283798324
    command: --data data/0/descriptors-1-million-reduced-128-normalized.data --dataeuc data/0/descriptors-1-million-reduced-128-normalized.data --size 1008263 --dimensions 128 --dataType numeric --nodesAddresses data/0/ips --testCases data/0/testcaseseuc --invocationCount 10 --warmUpIterations 1 --out data/0/out --seed 1283798324
    volumes:
     - C:\datasets\disa:/opt/docker/data
    links:
     - repetitionhandler1:repetitionhandler1
     - repetitionhandler2:repetitionhandler2

