version: '2'
services:
  repetitionhandler1:
    image: remeeh/repetitionhandler:latest
    volumes:
     - /home/remeeh/IdeaProjects/Distributed-LSH/data:/opt/docker/data
    environment:
      #- JAVA_OPTS="-Xms512M -Xmx1324M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M"
      - JAVA_OPTS=-Xmx1850M

  repetitionhandler2:
    image: remeeh/repetitionhandler:latest
    volumes:
     - /home/remeeh/IdeaProjects/Distributed-LSH/data:/opt/docker/data
    environment:
      #- JAVA_OPTS="-Xms512M -Xmx1324M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M"
      - JAVA_OPTS=-Xmx1850M

  recalltest:
    image: remeeh/recalltest:latest
    #command: --data data/0/descriptors-1-million-reduced-128-hamming-256bit.data --dataeuc data/0/descriptors-1-million-reduced-128-normalized.data --size 1008263 --dimensions 256 --dataType binary --nodesAddresses data/0/ips --testCases data/0/testcases --invocationCount 10 --warmUpIterations 1000 --out data/0/out --seed 1283798324
    command: --data data/0/descriptors-1-million-reduced-128-normalized.data --dataeuc data/0/descriptors-1-million-reduced-128-normalized.data --size 1008263 --setup single --dimensions 128 --dataType numeric --nodesAddresses data/0/ips --testCases data/0/testcases-norm-euc --invocationCount 10 --warmUpIterations 10 --out data/0/out --seed 1283798324
    #command: --data data/0/descriptors-1-million-reduced-128.data --dataeuc data/0/descriptors-1-million-reduced-128.data --size 1008263 --dimensions 128 --dataType numeric --nodesAddresses data/0/ips --testCases data/0/testcases-euc --invocationCount 10 --warmUpIterations 10 --out data/0/out --seed 1283798324
    volumes:
     - /home/remeeh/IdeaProjects/Distributed-LSH/data:/opt/docker/data
    links:
     - repetitionhandler1:repetitionhandler1
     - repetitionhandler2:repetitionhandler2
    environment:
      #- JAVA_OPTS="-Xms512M -Xmx1324M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M"
      - JAVA_OPTS=-Xmx1850M

