version: '2'
services:
  repetitionhandler1:
    image: remeeh/repetitionhandler:latest
    volumes:
     - ./data:/opt/docker/data

  repetitionhandler2:
    image: remeeh/repetitionhandler:latest
    volumes:
     - ./data:/opt/docker/data

  recalltest:
    image: remeeh/recalltest:latest
    volumes:
     - ./data:/opt/docker/data
    links:
     - repetitionhandler1:repetitionhandler1
     - repetitionhandler2:repetitionhandler2

