version: '2'
services:
  repetitionhandler1:
    image: remeeh/repetitionhandler:latest
    volumes:
     - /home/remeeh/IdeaProjects/Distributed-LSH/data/:/opt/docker/data
    environment:
      #- JAVA_OPTS="-Xms512M -Xmx1324M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M"
      - JAVA_OPTS=-Xmx1850M

  recalltest:
    image: remeeh/recalltest:latest
    command: --data data/ps-256-tiny.data --dataeuc data/profiset-128-float-tiny.data --size 500000 --setup distributed --dimensions 256 --dataType binary --nodesAddresses data/ips --testCases data/testcases-bin --invocationCount 1 --warmUpIterations 1 --out data/out --seed 54321
    #command: --data data/profiset-128-float-tiny.data --dataeuc data/profiset-128-float-tiny.data --size 500000 --setup distributed --dimensions 128 --dataType numeric --nodesAddresses data/ips --testCases data/testcases-euc --invocationCount 10 --warmUpIterations 2000 --out data/out --seed 1283798324
    volumes:
     - /home/remeeh/IdeaProjects/Distributed-LSH/data/:/opt/docker/data
    links:
     - repetitionhandler1:repetitionhandler1
    environment:
      #- JAVA_OPTS="-Xms512M -Xmx1324M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M"
      - JAVA_OPTS=-Xmx850M

