version: '2'
services:
  repetitionhandler1:
    image: remeeh/repetitionhandler:latest
    volumes:
     - ./data:/opt/docker/data

  repetitionhandler2:
    image: remeeh/repetitionhandler:latest
    volumes:
     - ./data:/opt/docker/data

